### ISSUE TITLE
Fatal error when creating new order

### ISSUE THREAD

**Issue by kidhab** [foodcoops/foodsoft#1011]
I seup a [demo](https://demo.foodcoops.net) version of the Foodsoft based on the latest commits of the master branch (use the usual credentials admin:secret).

Creating a new order results in a fatal error:
```
F, [2023-06-15T17:06:54.183950 #1394906] FATAL -- : [6c67fabc-c3c3-4ef7-8289-39067b49e9ff]   
[6c67fabc-c3c3-4ef7-8289-39067b49e9ff] ActionView::Template::Error (undefined method `*' for nil:NilClass):
[6c67fabc-c3c3-4ef7-8289-39067b49e9ff]     53:               = article.unit
[6c67fabc-c3c3-4ef7-8289-39067b49e9ff]     54:               - if article.unit_quantity > 1
[6c67fabc-c3c3-4ef7-8289-39067b49e9ff]     55:                 %span{style: 'color: grey'} &times; #{article.unit_quantity}#{pkg_helper_icon}
[6c67fabc-c3c3-4ef7-8289-39067b49e9ff]     56:           %td= "#{number_to_currency(article.price)} / #{number_to_currency(article.fc_price)}"
[6c67fabc-c3c3-4ef7-8289-39067b49e9ff]     57:     %tr
[6c67fabc-c3c3-4ef7-8289-39067b49e9ff]     58:       %td
[6c67fabc-c3c3-4ef7-8289-39067b49e9ff]     59:         = check_box_tag 'checkall', "1", false, { 'data-check-all' => '#articleList' }
[6c67fabc-c3c3-4ef7-8289-39067b49e9ff]   
[6c67fabc-c3c3-4ef7-8289-39067b49e9ff] app/models/concerns/price_calculation.rb:18:in `add_percent'
[6c67fabc-c3c3-4ef7-8289-39067b49e9ff] app/models/concerns/price_calculation.rb:12:in `fc_price'
```
I think it's linked to the Foodcoop margin configuration option. It this is not set at all it fails. If it's set (price_markup variable in the settings table is available regardless of the value) then it works.

**Comment by yksflip** [comment]
great kidhab! thanks for testing!
I think it's somehow assumed that default values for this are set in the app_config.yml maybe?
When there's a default value in app_config.yml it's not possible to set this config to nil via the admin interface.
Anyway, I think converting the field to a int and assuming 0% margin for a nil value, is  a good thing :)
