### ISSUE TITLE
Sporadic Message Errors

### ISSUE THREAD

**Issue by mortbauer** [foodcoops/foodsoft#1055]
Since I upgraded our foodsoft to 4.8.1 users are reporting problems sending messages, I could also reproduce it once, after restarting the server the problem was gone in my case. 
I was also able to isolate the logs for one such problem (I removed the message body because I think it is unrelated):
```
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.121226 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847] Started POST "/ruebezahl17/messages" for 213.142.96.93 at 2024-03-03 14:15:17 +0000
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.124339 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847] Processing by MessagesController#create as HTML
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.124664 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847]   Parameters: {"authenticity_token"=>"[FILTERED]", "message"=>{"reply_to"=>"", "send_method"=>"recipients", "workgroup_id"=>"45", "ordergroup_id"=>"264", "messagegroup_id"=>"170", "order_id"=>"2231", "recipient_tokens"=>"[FILTERED]", "private"=>"0", "subject"=>"Dein Kontoblatt", "body"=>""}, "commit"=>"Nachricht verschicken", "foodcoop"=>"ruebezahl17"}
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.206397 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847] Set locale to de
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.279499 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847] Completed 500 Internal Server Error in 155ms (ActiveRecord: 103.2ms | Allocations: 8272)
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.296609 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847]   Rendered /usr/local/bundle/gems/exception_notification-4.5.0/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (Duration: 11.0ms | Allocations: 3335)
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.665082 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847] Delivered mail 65e485f54927e_b822a60732c7@822efed581f2.mail (366.5ms)
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | F, [2024-03-03T14:15:17.668100 #184] FATAL -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847]   
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847] ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'recipients_ids' in 'field list'):
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847]   
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847] app/controllers/application_controller.rb:97:in `set_currency'
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847] app/controllers/application_controller.rb:85:in `set_time_zone'
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.669792 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847] Processing by ErrorsController#show as HTML
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.670146 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847]   Parameters: {"authenticity_token"=>"[FILTERED]", "message"=>{"reply_to"=>"", "send_method"=>"recipients", "workgroup_id"=>"45", "ordergroup_id"=>"264", "messagegroup_id"=>"170", "order_id"=>"2231", "recipient_tokens"=>"[FILTERED]", "private"=>"0", "subject"=>"Dein Kontoblatt", "body"=>"}, "commit"=>"Nachricht verschicken", "foodcoop"=>"ruebezahl17"}
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.680794 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847] Set locale to de
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.703175 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847]   Rendered errors/internal_server_error.html.haml within layouts/application (Duration: 2.3ms | Allocations: 341)
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.842519 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847]   Rendered layout layouts/application.html.haml (Duration: 141.7ms | Allocations: 23687)
fcat_foodsoft.1.qfrln2a3tbb6@v22018056292066830    | I, [2024-03-03T14:15:17.843133 #184]  INFO -- : [54dd8b7e-6d8e-48d7-a5ee-6db73cdb8847] Completed 500 Internal Server Error in 173ms (Views: 79.6ms | ActiveRecord: 70.7ms | Allocations: 27075)
```

Another pattern seems to be that it only occurs for answers to messages or creating messages to ordergoups.

I do not really get it for now since recipient_ids obviously shouldn't hit the db, however it seems it does.

**Comment by mortbauer** [comment]
Ok, gave it some more thinking, can it be that the message model is missing an: `attribute :recipients_ids` ?

**Comment by mortbauer** [comment]
I wrapped now the messages create controller in debug log level and and just look at the following lines which are the sql insert statements created for a short time window, first it produces the correct sql and suddenly it produces 4 times in a row the wrong:

```
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:14:06.048948 #149] DEBUG -- : [44393c94-c6e1-49e4-bf25-6ef02b14b4d0]   [1m[36mMessage Create (0.7ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `subject`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (20, 'Lagerbestellung läuft wieder', TRUE, '2024-03-09 10:14:06', NULL, NULL, 'j6I64SdH', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:29:41.672365 #171] DEBUG -- : [80d3a7f7-7d5a-4fb3-874b-99d6e429b17e]   [1m[36mMessage Create (0.6ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `subject`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (20, 'Kürrer-Bestellung für nächste Woche', FALSE, '2024-03-09 10:29:41', NULL, NULL, '/H9I2R/O', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:38:57.373712 #239] DEBUG -- : [baf1dd67-9bdc-44b3-b5e6-4d3e6cc661f4]   [1m[36mMessage Create (0.6ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `subject`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (24, 'Re: Lagerbestellung läuft wieder', TRUE, '2024-03-09 10:38:57', 507, NULL, 'd5zH39FH', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:44:20.513766 #199] DEBUG -- : [ee60dd35-e2ae-4b55-85dc-e4c47a44f3f2]   [1m[36mMessage Create (9.1ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `subject`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (31, 'Saiblinge abholbereit', TRUE, '2024-03-09 10:44:20', NULL, NULL, 'YzKTlLnb', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:49:07.028005 #171] DEBUG -- : [a3473ad3-c5e6-42d2-b11c-b8d6ede7e86a]   [1m[36mMessage Create (0.7ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `subject`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (114, 'Re: Re: Re: Re: Re: Huhn abgeholt?', TRUE, '2024-03-09 10:49:07', 8028, NULL, '8Zcinto5', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:51:26.762132 #212] DEBUG -- : [da144d92-78d6-4ea5-946e-b0c50bcc9f2e]   [1m[36mMessage Create (0.7ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `subject`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (55, 'BerSta Oster-Lieferung am MITTWOCH!', FALSE, '2024-03-09 10:51:26', NULL, NULL, 'zfABSJm6', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:52:52.445288 #212] DEBUG -- : [9868c2ef-a67c-4800-bf7f-24a2de03d92e]   [1m[36mMessage Create (0.7ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `subject`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (55, 'Re: Bubenicek Bestellung', FALSE, '2024-03-09 10:52:52', 3928, NULL, 'SuW8X8Qh', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:54:16.822190 #118] DEBUG -- : [87a2d605-a379-4b35-bd38-936035ccdf75]   [1m[36mMessage Create (1.2ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `recipients_ids`, `subject`, `email_state`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (55, NULL, 'Re: Re: Bubenicek Bestellung', 0, FALSE, '2024-03-09 10:54:16', 3928, NULL, 'HnaZk+5o', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:54:25.080435 #118] DEBUG -- : [33abf1bb-3763-4f72-a273-7751ef0cf90e]   [1m[36mMessage Create (1.2ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `recipients_ids`, `subject`, `email_state`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (55, NULL, 'Re: Re: Bubenicek Bestellung', 0, FALSE, '2024-03-09 10:54:25', 3928, NULL, 'gDv+zHyY', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:54:38.047763 #118] DEBUG -- : [1e6e3d3d-2c27-4373-bb0d-74a7117d03d7]   [1m[36mMessage Create (1.1ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `recipients_ids`, `subject`, `email_state`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (55, NULL, 'Re: Re: Bubenicek Bestellung', 0, FALSE, '2024-03-09 10:54:38', 3928, NULL, 'fKDUmR1V', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:54:42.818911 #118] DEBUG -- : [a08a414e-c633-4c12-972a-8d4a5f45b1e7]   [1m[36mMessage Create (1.1ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `recipients_ids`, `subject`, `email_state`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (55, NULL, 'Re: Re: Bubenicek Bestellung', 0, FALSE, '2024-03-09 10:54:42', 3928, NULL, 'Xr71gUT3', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:55:21.661033 #199] DEBUG -- : [5fe224b8-92e3-40e1-83d0-235c474a74b1]   [1m[36mMessage Create (0.5ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `subject`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (55, 'Re: Bubenicek Bestellung', FALSE, '2024-03-09 10:55:21', 3928, NULL, '37X9My8u', NULL)[0m
fcat_foodsoft.1.y7rmx5gllpzx@v22018056292066830    | D, [2024-03-09T10:55:40.908248 #199] DEBUG -- : [b50bf225-5edc-48bb-9e37-b9bddbe21fb6]   [1m[36mMessage Create (0.7ms)[0m  [1m[32mINSERT INTO `messages` (`sender_id`, `subject`, `private`, `created_at`, `reply_to`, `group_id`, `salt`, `received_email`) VALUES (114, 'Haslinger - Federvieh und Lamm', TRUE, '2024-03-09 10:55:40', NULL, NULL, 'r0Oq+yGi', NULL)[0m

```

**Comment by mortbauer** [comment]
This are the logs from more or less the same message once it worked and the other time it didn't.
[failed_transaction_debug.log](https://github.com/foodcoops/foodsoft/files/14546271/failed_transaction_debug.log)
[working_same_transaction.log](https://github.com/foodcoops/foodsoft/files/14546272/working_same_transaction.log)

**Comment by mortbauer** [comment]
I'm really stuck here, actually this seems to be really old code and suddenly it creates that strange behavior. And it is happening rather often so it is starting to get really troublesome.

**Comment by lentschi** [comment]
Hm... to be honest, for now, I have no clue :worried: I also cannot reproduce this locally - maybe it's some issue only occurring with certain production environment settings.

@yksflip Have you ever experienced this error on your servers?

It seems like some kind of rails association caching bug to me, so maybe upgrading rails' (or some other component's) patch version might help. I couldn't find a rails issue for this on GitHub though.

What you could try, is add this temporary line at the top of `MessagesController#create:

```ruby
Rails.logger.info "---TMP DUMMY: #{Message.first.recipients.first.id}"
```

In the best case, this could even somehow _force_ rails to reload the missing association config before trying to save the message. In the worst case it would throw a similar error three lines earlier.

**Comment by yksflip** [comment]
this sounds really tricky. I haven't heard of this issue before.

I cannot make any sense why it tries to write `recipients_ids` into the `message` table. I mean it might used to be like that before the `MessageRecipient` was introduced, but that's long ago. 

@lentschi I don't quite understand why this might be a association caching bug, could you maybe explain this? The association is called  `message_recipients` but here it tries to save to a column called `recipients_ids` ...

**Comment by lentschi** [comment]
@yksflip 
> The association is called message_recipients but here it tries to save to a column called recipients_ids ...

Yes, but there's the `recipients` association too - see https://github.com/foodcoops/foodsoft/blob/790a2637aa937aee9e6c44d3991d7a16228fc4bc/plugins/messages/app/models/message.rb#L8

So my only guess for now is that active records' associations get confused _somehow_. (Maybe depending on the order of importing some plugin or whatever... :shrug: )

I'm afraid, I don't have too much time to investigate right now. Should the bug still be there come Friday, I can try to debug.

**Comment by lentschi** [comment]
Debugged a little more but still couldn't find a lead. :worried: 

@mortbauer 
When adding the suggested debug log, you could also add `Rails.logger.info "---TMP DUMMY message columns: #{Message.column_names}"`.
That _should_ result in `["id", "sender_id", "subject", "private", "created_at", "reply_to", "group_id", "salt", "received_email"]`, but I have an inkling, that in the error case it will also include `recipients_ids`.

What we could also add a debug log for is `Message#create_message_recipients` - maybe the `before_validation` handler isn't run for some reason. (But actually I commented it out locally and still don't see any errors related to db queries - the `save` just fails with a validation error then (see `validates_presence_of :message_recipients`).

**Comment by mortbauer** [comment]
Thank you for looking into it, but I think I got rid of the problem with these two commits, 
[1fa917291452c03cc05e8788140650d701f1a308](https://github.com/mortbauer/foodsoft/commit/1fa917291452c03cc05e8788140650d701f1a308),[92a59018b4da23cc369c41da35cc318d7feff715](https://github.com/mortbauer/foodsoft/commit/92a59018b4da23cc369c41da35cc318d7feff715).
The foodsoft is now running with these since almost one week and the error did not show up anymore. So I'm now cleaning it from the debug prints and bring it our main branch.
