### ISSUE TITLE
Pickup screen cannot be shown with old orders

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodsoft#537]
After I ran database migrations with existing orders, then opening the new pickups screen (from #358), I saw an error:
```
I18n::ArgumentError - Object must be a Date, DateTime or Time object. nil given.:
  app/views/pickups/index.html.haml:5:in `block (2 levels) in _33c0e08d345821b4982f46f0f042b8e0'
  app/views/pickups/index.html.haml:4:in `block in _33c0e08d345821b4982f46f0f042b8e0'
  app/views/pickups/index.html.haml:3:in `_33c0e08d345821b4982f46f0f042b8e0'
  app/controllers/application_controller.rb:228:in `set_currency'
  app/controllers/application_controller.rb:216:in `set_time_zone'
```

I think we need to allow for `nil` pickup values (or update the migration to set something sensible).

**Comment by paroga** [comment]
Fixed on master

**Comment by wvengen** [comment]
Thanks :)
