### ISSUE TITLE
Group PDF and Matrix PDF are broken

### ISSUE THREAD

**Issue by carchrae** [foodcoops/foodsoft#647]
it appears there was some change to the scopes (i hope it wasn't me!) or something along those lines.  these reports now fail.  Article PDF is still working.

http://localhost:3000/f/orders/1.pdf?document=groups
http://localhost:3000/f/orders/1.pdf?document=matrix

```
ActiveRecord::StatementInvalid (PG::GroupingError: ERROR:  column "group_orders.ordergroup_id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT groups.name, SUM(group_orders.price), "group_orders"....
                                                     ^
: SELECT groups.name, SUM(group_orders.price), "group_orders"."ordergroup_id" FROM "group_orders" LEFT OUTER JOIN "groups" ON "groups"."id" = "group_orders"."ordergroup_id" AND "groups"."type" IN ('Ordergroup') WHERE "group_orders"."order_id" = 121 GROUP BY groups.id  ORDER BY groups.name):
  lib/order_pdf.rb:76:in `ordergroups'
  lib/order_pdf.rb:88:in `each_ordergroup'
  app/documents/order_by_groups.rb:14:in `body'
  lib/render_pdf.rb:119:in `to_pdf'
  app/controllers/concerns/send_order_pdf.rb:14:in `send_order_pdf'
  app/controllers/orders_controller.rb:50:in `block (2 levels) in show'
  app/controllers/orders_controller.rb:44:in `show'
  app/controllers/application_controller.rb:93:in `set_currency'
  app/controllers/application_controller.rb:81:in `set_time_zone'
```

**Comment by carchrae** [comment]
this did it: https://github.com/foodcoops/foodsoft/commit/d925533366ab108de6dd0d1feaed2098fdcc2ee7#diff-2a18bbe83b881ac142168ad54a25ee65

i'll submit a patch to revert it, but it'll probably break whatever @paroga was trying to fix.

**Comment by wvengen** [comment]
Ouch, thanks for looking at this.
I guess we could use some specs for PDFs as well.
