### ISSUE TITLE
`unit_quantity == 0` causes 500 when viewing `group_order`

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodsoft#710]
Steps to reproduce:
 * Set `unit_quantity` of some article to zero (bypass validation via shared-article sync and rounding towards zero).
 * Create an order including that article. Let's say the id is `78`.
 * Visit [the page for ordering](https://app.foodcoops.net/demo/group_orders/new?order_id=78) (yes, you can actually see the error in the demo).

As a quick fix, you can [edit the order](https://app.foodcoops.net/demo/orders/78/edit) and disable the checkbox of the problematic article.

> ```
> ZeroDivisionError (divided by 0):
>   app/models/order_article.rb:242:in `%'
>   app/models/order_article.rb:242:in `_missing_units'
>   app/models/order_article.rb:191:in `missing_units'
>   app/models/group_order.rb:47:in `block (2 levels) in load_data'
>   app/models/group_order.rb:31:in `each'
>   app/models/group_order.rb:31:in `block in load_data'
>   app/models/group_order.rb:30:in `each'
>   app/models/group_order.rb:30:in `load_data'
>   app/controllers/group_orders_controller.rb:17:in `new'
>   app/controllers/application_controller.rb:228:in `set_currency'
>   app/controllers/application_controller.rb:216:in `set_time_zone'
> ```

Here are some links to relevant lines in v4.6.0:

- [app/models/order_article.rb:242:in `%'](https://github.com/foodcoops/foodsoft/blob/d7420a13d2fafb91a9687c7d09e48c7cc279c3c5/app/models/order_article.rb#L242)
- [app/models/order_article.rb:191:in `missing_units'](https://github.com/foodcoops/foodsoft/blob/d7420a13d2fafb91a9687c7d09e48c7cc279c3c5/app/models/group_order.rb#L47)
- [app/models/group_order.rb:30:in `load_data'](https://github.com/foodcoops/foodsoft/blob/d7420a13d2fafb91a9687c7d09e48c7cc279c3c5/app/models/group_order.rb#L30)

**Comment by JuliusR** [comment]
In fact, the real bug is the bypassing of [validation](https://github.com/foodcoops/foodsoft/blob/d3dc70f87b6e54d097a7afd6f076fd7812085377/app/models/article.rb#L61) via the [shared-article sync (use the green "sync" button in the action bar](https://app.foodcoops.net/demo/suppliers/32/articles).

We can also simplify the manual prevention of `unit_quantity == 0` by #675.
