### ISSUE TITLE
internal server error when saving configuration with order_schedule

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodsoft#801]
Saving the admin config (PATCH "/demo/admin/config") fails with an internal server error if `order_schedule` is used.

```
NoMethodError (undefined method `to_ical' for #<ActionController::Parameters:0x00007f8d38fdbde0>):
app/controllers/admin/configs_controller.rb:48:in `block in parse_recurring_selects!'
app/controllers/admin/configs_controller.rb:43:in `each'
app/controllers/admin/configs_controller.rb:43:in `parse_recurring_selects!'
app/controllers/admin/configs_controller.rb:18:in `update'
app/controllers/application_controller.rb:94:in `set_currency'
app/controllers/application_controller.rb:82:in `set_time_zone'
```

This can be reproduced with the [demo](https://app.foodcoops.net/demo/admin/config). Here are the parameters that cause the failure:
```
{
  # [omitting irrelevant params]
  'config' => {
    # [omitting irrelevant options]
    'order_schedule' => {
      'boxfill' => { 'recurr' => 'null', 'time' => '' },
      'ends' => {
        'recurr' =>
          "{\"interval\":1,\"until\":null,\"count\":null,\"validations\":null,\"rule_type\":\"IceCube::DailyRule\"}",
        'time' => '10',
      },
    },
  },
}
```
With the following parameters, saving the new configuration succeeds.
```
{
  # [omitting irrelevant params]
  'config' => {
    # [omitting irrelevant options]
    'order_schedule' => {
      'boxfill' => { 'recurr' => 'null', 'time' => '' },
      'ends' => { 'recurr' => '{}', 'time' => '10' },
    },
  },
}
```

**Comment by JuliusR** [comment]
According to a user report, this problems has been there for a while already. It is unfortunate that the error reporting is broken. Does anyone know how to fix foodcoops/foodcoops.net#35?

**Comment by mortbauer** [comment]
Hey @yksflip, I'm trying to get your current master branch to our foodcoopsat site and stumbled over this bug which I was able to resolve within pull #1042.
