### ISSUE TITLE
Random failure to connect to MySQL db

### ISSUE THREAD

**Issue by alexanderharm** [foodcoops/foodsoft#941]
Hi,

every other week or so I receive the following error message:

```
[Foodsoft] (Mysql2::Error::ConnectionError) "Can't connect to MySQL server on 'foodsoft-db' (99)"

A Mysql2::Error::ConnectionError occurred in background at [2022-04-21 19:00:33 UTC](canary:event?ts=672260438.00) : 

Can't connect to MySQL server on 'foodsoft-db' (99) 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect' 

------------------------------- 
Backtrace: 
------------------------------- 

/usr/src/app/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_handling.rb:118:in `retrieve_connection' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_handling.rb:90:in `connection' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/model_schema.rb:324:in `table_exists?' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/attribute_methods.rb:151:in `attribute_method?' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/date_time_attribute-0.1.2/lib/date_time_attribute.rb:57:in `block in date_time_attribute' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/date_time_attribute-0.1.2/lib/date_time_attribute.rb:55:in `each' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/date_time_attribute-0.1.2/lib/date_time_attribute.rb:55:in `date_time_attribute' 
/usr/src/app/lib/date_time_attribute_validate.rb:11:in `date_time_attribute' 
/usr/src/app/app/models/order.rb:45:in `<class:Order>' 
/usr/src/app/app/models/order.rb:3:in `<main>' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:378:in `block in require_or_load' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `block in load_interlock' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:13:in `loading' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `load_interlock' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:356:in `require_or_load' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in require_or_load' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `require_or_load' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:510:in `load_missing_constant' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:195:in `const_missing' 
/usr/src/app/lib/tasks/foodsoft.rake:6:in `block (2 levels) in <main>' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute' 
/usr/src/app/lib/tasks/multicoops.rake:14:in `block (3 levels) in <main>' 
/usr/src/app/lib/foodsoft_config.rb:165:in `block in each_coop' 
/usr/src/app/lib/foodsoft_config.rb:163:in `each' 
/usr/src/app/lib/foodsoft_config.rb:163:in `each_coop' 
/usr/src/app/lib/tasks/multicoops.rake:11:in `block (2 levels) in <main>' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain' 
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run' 
/usr/src/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>' 
/usr/src/app/vendor/bundle/ruby/2.6.0/bin/rake:23:in `load' 
/usr/src/app/vendor/bundle/ruby/2.6.0/bin/rake:23:in `<top (required)>' 
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load' 
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load' 
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run' 
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec' 
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run' 
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command' 
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch' 
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch' 
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start' 
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:18:in `start' 
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>' 
/usr/local/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors' 
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>' 
/usr/local/bin/bundle:23:in `load' 
/usr/local/bin/bundle:23:in `<main>' 

------------------------------- 
Data: 
------------------------------- 

* data: {:foodcoop=>"f"}
```

In general foodsoft runs fine so I'm a bit confused because the db connection must be established most of the time...

**Comment by wvengen** [comment]
Hi, too bad it doesn't always work perfectly!
I can't see too much about it, it highly depends on your setup.
One thing could be that your database server is not yet available when the worker(?) starts.
